default: &default
  adapter: postgresql
  encoding: unicode
  pool: 10
  timeout: 10000
  port: 5432

development:
  <<: *default
  host: <%= ENV["POSTGRES_HOST"] {'localhost'} %>
  username: <%= ENV["POSTGRES_USER"] %>
  password: <%= ENV["POSTGRES_PASSWORD"] %>
  database: golfr_dev

test:
  <<: *default
  database: golfr_test

production:
  <<: *default
