default: &default
  adapter: postgresql
  encoding: unicode
  pool: 10
  timeout: 10000
  port: 5432
  host: localhost
  username: postgres
  password: postgres

development:
  <<: *default
  database: golfr_dev

test:
  <<: *default
  database: golfr_test

production:
  <<: *default
